"""transaction costs

Revision ID: 0ffb9a93fa54
Revises: d1cf6884fb74
Create Date: 2024-11-17 16:04:59.089055

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = "0ffb9a93fa54"
down_revision = "d1cf6884fb74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    currency_enum = ENUM("EUR", "USD", "GBP", name="currency", create_type=False)
    op.create_table(
        "transaction_cost",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column(
            "currency",
            currency_enum,
            nullable=False,
        ),
        sa.Column("commission_order_value", sa.Float(), nullable=True),
        sa.Column("commission_per_share", sa.Float(), nullable=True),
        sa.Column("minimum_commission", sa.Float(), nullable=True),
        sa.Column("taxes", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platform.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_cost")
    # ### end Alembic commands ###
