"""new entry date from submit

Revision ID: b48661df2b5d
Revises: a2af52dba3ad
Create Date: 2024-01-03 00:08:40.824002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48661df2b5d'
down_revision = 'a2af52dba3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_form_data', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
